### ISSUE TITLE
Change repo name and readme to match package name?

### ISSUE THREAD

**Issue by karlhorky** [Viijay-Kr/typescript-cleanup-definitions#6]
The repo name and readme mention `typescript-cleanup-defs`, which is a [404 on npm](https://www.npmjs.com/package/typescript-cleanup-defs)

![Screenshot 2024-08-22 at 09 28 05](https://github.com/user-attachments/assets/8f3c0e39-8cc5-491e-962b-2fb1ed7cd3fc)

It appears the official package name is [`typescript-cleanup-definitions`](https://www.npmjs.com/package/typescript-cleanup-definitions)

Maybe the repo name and readme should be updated to reflect that?

**Comment by Viijay-Kr** [comment]
@karlhorky Sure sounds good

**Comment by Viijay-Kr** [comment]
Done

**Comment by karlhorky** [comment]
Nice, thanks!
