### ISSUE TITLE
Add GitHub releases with release notes?

### ISSUE THREAD

**Issue by karlhorky** [Viijay-Kr/typescript-cleanup-definitions#7]
What do you think about creating GitHub releases on [the Releases page](https://github.com/Viijay-Kr/typescript-cleanup-defs/releases) for every page, with release notes?

Options:

1. Setting up a tool such as [Changesets](https://github.com/changesets/changesets) or [Release It!](https://github.com/release-it/release-it) (or any of the many others)
2. Use [the built-in release notes generator in the GitHub UI](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

**Comment by Viijay-Kr** [comment]
@karlhorky . Generating release notes and release pages sounds good to me. 

I m hoping changesets also generate release notes right ?

**Comment by karlhorky** [comment]
> changesets also generate release notes right

It looks like [the action](https://github.com/changesets/action) writes the bullet points of what could be considered release notes, in the `CHANGELOG.md` file:

- https://github.com/Viijay-Kr/react-ts-css/pull/168

However it appears that the `changeset` CLI doesn't yet automate publishing new GitHub Releases?

- https://github.com/changesets/changesets/issues/885

But maybe the action is enough.
